### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by TogetherYH** [BearCooike/ssFPN-pytorch#1]
你好，关于ssFPN这个可以交流一下嘛？

**Comment by BearCooike** [comment]
你好，有什么可以帮助到你的吗？

**Comment by TogetherYH** [comment]
关于ssFPN这个，请问有没有更全的代码实现呢？

**Comment by BearCooike** [comment]
该实现就是ssFPN的完整实现，如果需要带ssFPN的yolov4或yoloR，可以等官方开源。
如果需要将ssFPN作为插件引入自己的算法项目，请自己操作

**Comment by TogetherYH** [comment]
好的 感谢
